#!/bin/sh
# $Id$
# post remove script for the Debian GNU/Linux slack package

set -e

if [ "$1" = "purge" ]; then
        # purge the source cache as well
        echo "Purging local source cache"
        rm -r /var/lib/slack-master/source

        if getent passwd slack >/dev/null; then
            echo "Removing user slack"
            deluser slack
        fi
        if getent group slack >/dev/null; then
            echo "Removing group slack"
            delgroup slack
        fi

fi

exit 0
