#!/bin/sh
# $Id$
# post remove script for the Debian GNU/Linux slack package

set -e

if [ "$1" = "purge" ]; then
        # purge the source cache as well
        echo "Purging local source cache"
        rm -rf /var/lib/slack/home/source
fi

exit 0
