.\" $Header$
.\" vim:tw=72:filetype=nroff
.\"
.\"       manpage for slack-update-source
.\"
.TH slack-update-source 8 2005-03-12 "slack-master" "Administrative commands" 

.SH NAME
slack\-update\-source - Update the slack master source directory

.SH SYNOPSIS

\fBslack\-update\-source\fR

.SH DESCRIPTION

slack\-update\-source does a CVS checkout of the slack master source
directory, so that your changes to the CVS repository can be distributed
to machines running slack.

.SH OPTIONS

slack\-update\-source takes no options.

.SH SEE ALSO
.BR slack(8)
