#!/bin/sh
# $Id$
# post remove script for the Debian GNU/Linux slack package

set -e

if [ "$1" = "purge" ]; then
        rm -f /etc/slack.conf
        # purge the cache as well
        rm -rf /var/lib/slack/cache
fi

exit 0
